version: "3"
services:
  react-app:
    image: react-app
    build: ./client/
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-network
    volumes:
      - ./client/:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - WDS_SOCKET_HOST=127.0.0.1 
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true 
  api-server:
    image: api-server
    build: ./server/
    ports:
      - "5000:5000"
    networks:
      - mern-network
    volumes: 
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
networks:
  mern-network:
    driver: "bridge"
